export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/role-select/index',
    'pages/persona-select/index',
    'pages/home/index',
    'pages/chat/index',
    'pages/history/index',
    'pages/knowledge/index',
    'pages/knowledge/add',
    'pages/memories/index',
    'pages/profile/index',
    'pages/teacher-students/index',
    'pages/my-teachers/index',
    'pages/student-detail/index',
    'pages/share-join/index',
    'pages/class-create/index',
    'pages/class-detail/index',
    'pages/class-edit/index',
    'pages/knowledge/preview',
    'pages/persona-overview/index',
    'pages/student-chat-history/index',
    'pages/discover/index',
    'pages/share-manage/index',
    'pages/memory-manage/index',
    'pages/teacher-message/index',
    'pages/curriculum-config/index',
    'pages/feedback/index',
    'pages/feedback-manage/index',
    'pages/student-batch/index',
    'pages/student-profile/index',
    'pages/approval-manage/index',
    'pages/approval-detail/index',
    'pages/chat-list/index',
    'pages/my-comments/index',
    'pages/course-publish/index',
    'pages/course-list/index',
    'pages/test-student/index',
  ],
  tabBar: {
    custom: true,
    color: '#999999',
    selectedColor: '#4F46E5',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      // 教师端和学生端共用的 TabBar 页面
      {
        pagePath: 'pages/chat-list/index',
        text: '聊天列表',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home_selected.png',
      },
      {
        pagePath: 'pages/home/index',
        text: '对话',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home_selected.png',
      },
      {
        pagePath: 'pages/discover/index',
        text: '发现',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home_selected.png',
      },
      {
        pagePath: 'pages/teacher-students/index',
        text: '学生管理',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home_selected.png',
      },
      {
        pagePath: 'pages/knowledge/index',
        text: '知识库',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home_selected.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabbar/profile.png',
        selectedIconPath: 'assets/tabbar/profile_selected.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#4F46E5',
    navigationBarTitleText: 'AI 数字分身',
    navigationBarTextStyle: 'white',
  },
})
